language: ruby
rvm:
- 2.0.0
install:
- bundle install --without production --deployment
- npm install
cache:
  directories:
  - vendor/bundle
  - node_modules
script: bundle exec jekyll build --trace
branches:
  only:
  - gh-pages
