# Site settings
title: "Realtime JSer.info"
email: "info@efcl.info"
description: "リアルタイム版JSer.info"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://realtime.jser.info" # the base hostname & protocol for your site
twitter_username: jser_info
github_username:  jser
timezone: Asia/Tokyo
encoding: utf-8
exclude:
  - "README.md"
  - "Gemfile"
  - "LICENSE"
  - "bower.json"
  - "package.json"
  - "test/"
  - "vendor"
  - "node_modules"
# Build settings
markdown: redcarpet
exclude:
    - node_modules
